export {
  claimApi,
  useGetAttachmentTypesQuery,
  useGetClientDemandsQuery,
  useGetFlawsQuery,
  useGetReasonsQuery,
  useLazyGetAttachmentTypesQuery,
  useLazyGetClientDemandsQuery,
  useLazyGetFlawsQuery,
  useLazyGetReasonsQuery,
} from './api/claimApi';
export type {
  AddAttachmentsQueryParams,
  AddAttachmentsResponse,
  AttachmentStatus,
  AttachmentType,
  ClaimAttachment,
  ClaimAttachmentMetadata,
  ClaimActionResponse,
  ClaimDataResponse,
  ClaimDictionaryItem,
  ClaimErrorResponse,
  ClaimFlaw,
  CreateClaimQueryParams,
  CreateClaimResponse,
  GetAttachmentTypesResponse,
  GetClientDemandsResponse,
  GetFlawsQueryParams,
  GetFlawsResponse,
  GetReasonsResponse,
} from './model/claimTypes';
